/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    founders: FounderAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    founders: Founder;
    media: Media;
    stories: Story;
    categories: Category;
    tags: Tag;
    industries: Industry;
    organizations: Organization;
    startups: Startup;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    founders: FoundersSelect<false> | FoundersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    startups: StartupsSelect<false> | StartupsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Founder;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface FounderAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  slug: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  uploadedBy?: (number | null) | Founder;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Filter by moderationStatus = pending or needsReview = true to work the moderation queue.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founders".
 */
export interface Founder {
  id: number;
  name: string;
  slug: string;
  headline?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  avatar?: (number | null) | Media;
  /**
   * Public URL from Supabase Storage (set by founder account uploads).
   */
  avatarUrl?: string | null;
  gender?: ('female' | 'male' | 'non-binary' | 'prefer-not-to-say' | 'other') | null;
  city?: string | null;
  state?: string | null;
  /**
   * ISO state code from location picker (e.g. KA).
   */
  stateCode?: string | null;
  country?: string | null;
  cohortName?: string | null;
  cohortYear?: number | null;
  linkedIn?: string | null;
  twitter?: string | null;
  website?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  youtube?: string | null;
  github?: string | null;
  industries?: (number | Industry)[] | null;
  organizations?: (number | Organization)[] | null;
  lookingForCoFounder?: boolean | null;
  openToOpportunities?: boolean | null;
  /**
   * Denormalized for profile rendering. Startups.team is authoritative.
   */
  linkedStartups?: (number | Startup)[] | null;
  needsReview?: boolean | null;
  moderationStatus: 'draft' | 'pending' | 'approved';
  verificationStatus: 'pending' | 'verified' | 'rejected';
  verificationSource?: {
    type?: ('organization' | 'manual') | null;
    organization?: (number | null) | Organization;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'founders';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  slug: string;
  type:
    | 'incubator'
    | 'accelerator'
    | 'investor'
    | 'venture-capital'
    | 'angel-network'
    | 'university'
    | 'startup-community'
    | 'government-program'
    | 'coworking-space'
    | 'innovation-hub'
    | 'corporate-innovation'
    | 'other';
  status: 'draft' | 'published';
  location?: string | null;
  website?: string | null;
  description?: string | null;
  logo?: (number | null) | Media;
  parentOrganization?: (number | null) | Organization;
  updatedAt: string;
  createdAt: string;
}
/**
 * Filter by moderationStatus = pending, needsReview = true, or claim.claimStatus = pending.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "startups".
 */
export interface Startup {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  /**
   * Public URL from Supabase Storage (set by founder account uploads).
   */
  logoUrl?: string | null;
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  website?: string | null;
  linkedIn?: string | null;
  twitter?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  youtube?: string | null;
  github?: string | null;
  industry?: (number | null) | Industry;
  stage?: ('idea' | 'mvp' | 'early-revenue' | 'growth' | 'scaling') | null;
  city?: string | null;
  state?: string | null;
  /**
   * ISO state code from location picker (e.g. KA).
   */
  stateCode?: string | null;
  country?: string | null;
  cohortName?: string | null;
  cohortYear?: number | null;
  teamSize?: number | null;
  organizations?: (number | Organization)[] | null;
  fundingStatus?: string | null;
  foundedYear?: number | null;
  womenLed?: boolean | null;
  isHiring?: boolean | null;
  isRaising?: boolean | null;
  isLookingForCoFounder?: boolean | null;
  team?:
    | {
        /**
         * Display name for team members not linked to a FoS founder profile.
         */
        name?: string | null;
        founder?: (number | null) | Founder;
        role: 'founder' | 'co-founder' | 'ceo' | 'cto' | 'cpo' | 'advisor';
        isPrimary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  owner?: (number | null) | Founder;
  claim?: {
    claimedBy?: (number | null) | Founder;
    claimedAt?: string | null;
    claimStatus?: ('unclaimed' | 'pending' | 'claimed') | null;
  };
  needsReview?: boolean | null;
  moderationStatus: 'draft' | 'pending' | 'approved';
  verificationStatus: 'pending' | 'verified' | 'rejected';
  opportunities?:
    | {
        type: 'job' | 'internship' | 'co-founder' | 'partnership';
        title: string;
        description?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  author: number | User;
  category?: (number | null) | Category;
  tags?: (number | Tag)[] | null;
  publishedDate: string;
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'founders';
        value: number | Founder;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'startups';
        value: number | Startup;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'founders';
        value: number | Founder;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'founders';
        value: number | Founder;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founders_select".
 */
export interface FoundersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  headline?: T;
  bio?: T;
  avatar?: T;
  avatarUrl?: T;
  gender?: T;
  city?: T;
  state?: T;
  stateCode?: T;
  country?: T;
  cohortName?: T;
  cohortYear?: T;
  linkedIn?: T;
  twitter?: T;
  website?: T;
  instagram?: T;
  facebook?: T;
  youtube?: T;
  github?: T;
  industries?: T;
  organizations?: T;
  lookingForCoFounder?: T;
  openToOpportunities?: T;
  linkedStartups?: T;
  needsReview?: T;
  moderationStatus?: T;
  verificationStatus?: T;
  verificationSource?:
    | T
    | {
        type?: T;
        organization?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  category?: T;
  tags?: T;
  publishedDate?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  status?: T;
  location?: T;
  website?: T;
  description?: T;
  logo?: T;
  parentOrganization?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "startups_select".
 */
export interface StartupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  logoUrl?: T;
  tagline?: T;
  description?: T;
  website?: T;
  linkedIn?: T;
  twitter?: T;
  instagram?: T;
  facebook?: T;
  youtube?: T;
  github?: T;
  industry?: T;
  stage?: T;
  city?: T;
  state?: T;
  stateCode?: T;
  country?: T;
  cohortName?: T;
  cohortYear?: T;
  teamSize?: T;
  organizations?: T;
  fundingStatus?: T;
  foundedYear?: T;
  womenLed?: T;
  isHiring?: T;
  isRaising?: T;
  isLookingForCoFounder?: T;
  team?:
    | T
    | {
        name?: T;
        founder?: T;
        role?: T;
        isPrimary?: T;
        id?: T;
      };
  owner?: T;
  claim?:
    | T
    | {
        claimedBy?: T;
        claimedAt?: T;
        claimStatus?: T;
      };
  needsReview?: T;
  moderationStatus?: T;
  verificationStatus?: T;
  opportunities?:
    | T
    | {
        type?: T;
        title?: T;
        description?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}