/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  type AnyPgColumn,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", ["admin", "editor"]);
export const enum_founders_gender = pgEnum("enum_founders_gender", [
  "female",
  "male",
  "non-binary",
  "prefer-not-to-say",
  "other",
]);
export const enum_founders_moderation_status = pgEnum(
  "enum_founders_moderation_status",
  ["draft", "pending", "approved"],
);
export const enum_founders_verification_status = pgEnum(
  "enum_founders_verification_status",
  ["pending", "verified", "rejected"],
);
export const enum_founders_verification_source_type = pgEnum(
  "enum_founders_verification_source_type",
  ["organization", "manual"],
);
export const enum_stories_status = pgEnum("enum_stories_status", [
  "draft",
  "published",
]);
export const enum__stories_v_version_status = pgEnum(
  "enum__stories_v_version_status",
  ["draft", "published"],
);
export const enum_organizations_type = pgEnum("enum_organizations_type", [
  "incubator",
  "accelerator",
  "community",
  "university",
  "government-program",
]);
export const enum_startups_team_role = pgEnum("enum_startups_team_role", [
  "founder",
  "co-founder",
  "ceo",
  "cto",
  "cpo",
  "advisor",
]);
export const enum_startups_opportunities_type = pgEnum(
  "enum_startups_opportunities_type",
  ["job", "internship", "co-founder", "partnership"],
);
export const enum_startups_stage = pgEnum("enum_startups_stage", [
  "idea",
  "mvp",
  "early-revenue",
  "growth",
  "scaling",
]);
export const enum_startups_claim_claim_status = pgEnum(
  "enum_startups_claim_claim_status",
  ["unclaimed", "pending", "claimed"],
);
export const enum_startups_moderation_status = pgEnum(
  "enum_startups_moderation_status",
  ["draft", "pending", "approved"],
);
export const enum_startups_verification_status = pgEnum(
  "enum_startups_verification_status",
  ["pending", "verified", "rejected"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    bio: varchar("bio"),
    avatar: integer("avatar_id").references(() => media.id, {
      onDelete: "set null",
    }),
    role: enum_users_role("role").notNull().default("editor"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    uniqueIndex("users_slug_idx").on(columns.slug),
    index("users_avatar_idx").on(columns.avatar),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const founders_sessions = pgTable(
  "founders_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("founders_sessions_order_idx").on(columns._order),
    index("founders_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [founders.id],
      name: "founders_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const founders = pgTable(
  "founders",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    headline: varchar("headline"),
    bio: jsonb("bio"),
    avatar: integer("avatar_id").references((): AnyPgColumn => media.id, {
      onDelete: "set null",
    }),
    gender: enum_founders_gender("gender"),
    city: varchar("city"),
    state: varchar("state"),
    country: varchar("country"),
    linkedIn: varchar("linked_in"),
    twitter: varchar("twitter"),
    website: varchar("website"),
    lookingForCoFounder: boolean("looking_for_co_founder").default(false),
    openToOpportunities: boolean("open_to_opportunities").default(false),
    needsReview: boolean("needs_review").default(false),
    moderationStatus: enum_founders_moderation_status("moderation_status")
      .notNull()
      .default("pending"),
    verificationStatus: enum_founders_verification_status("verification_status")
      .notNull()
      .default("pending"),
    verificationSource_type: enum_founders_verification_source_type(
      "verification_source_type",
    ),
    verificationSource_organization: integer(
      "verification_source_organization_id",
    ).references((): AnyPgColumn => organizations.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    uniqueIndex("founders_slug_idx").on(columns.slug),
    index("founders_avatar_idx").on(columns.avatar),
    index("founders_city_idx").on(columns.city),
    index("founders_needs_review_idx").on(columns.needsReview),
    index("founders_moderation_status_idx").on(columns.moderationStatus),
    index("founders_verification_status_idx").on(columns.verificationStatus),
    index("founders_verification_source_verification_source_organiz_idx").on(
      columns.verificationSource_organization,
    ),
    index("founders_updated_at_idx").on(columns.updatedAt),
    index("founders_created_at_idx").on(columns.createdAt),
    uniqueIndex("founders_email_idx").on(columns.email),
    index("city_idx").on(columns.city),
    index("moderationStatus_idx").on(columns.moderationStatus),
    index("verificationStatus_idx").on(columns.verificationStatus),
    index("needsReview_idx").on(columns.needsReview),
  ],
);

export const founders_rels = pgTable(
  "founders_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    industriesID: integer("industries_id"),
    organizationsID: integer("organizations_id"),
    startupsID: integer("startups_id"),
  },
  (columns) => [
    index("founders_rels_order_idx").on(columns.order),
    index("founders_rels_parent_idx").on(columns.parent),
    index("founders_rels_path_idx").on(columns.path),
    index("founders_rels_industries_id_idx").on(columns.industriesID),
    index("founders_rels_organizations_id_idx").on(columns.organizationsID),
    index("founders_rels_startups_id_idx").on(columns.startupsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [founders.id],
      name: "founders_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["industriesID"]],
      foreignColumns: [industries.id],
      name: "founders_rels_industries_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["organizationsID"]],
      foreignColumns: [organizations.id],
      name: "founders_rels_organizations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["startupsID"]],
      foreignColumns: [startups.id],
      name: "founders_rels_startups_fk",
    }).onDelete("cascade"),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    uploadedBy: integer("uploaded_by_id").references(
      (): AnyPgColumn => founders.id,
      {
        onDelete: "set null",
      },
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumb_url: varchar("sizes_thumb_url"),
    sizes_thumb_width: numeric("sizes_thumb_width", { mode: "number" }),
    sizes_thumb_height: numeric("sizes_thumb_height", { mode: "number" }),
    sizes_thumb_mimeType: varchar("sizes_thumb_mime_type"),
    sizes_thumb_filesize: numeric("sizes_thumb_filesize", { mode: "number" }),
    sizes_thumb_filename: varchar("sizes_thumb_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_og_url: varchar("sizes_og_url"),
    sizes_og_width: numeric("sizes_og_width", { mode: "number" }),
    sizes_og_height: numeric("sizes_og_height", { mode: "number" }),
    sizes_og_mimeType: varchar("sizes_og_mime_type"),
    sizes_og_filesize: numeric("sizes_og_filesize", { mode: "number" }),
    sizes_og_filename: varchar("sizes_og_filename"),
  },
  (columns) => [
    index("media_uploaded_by_idx").on(columns.uploadedBy),
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumb_sizes_thumb_filename_idx").on(
      columns.sizes_thumb_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_og_sizes_og_filename_idx").on(columns.sizes_og_filename),
  ],
);

export const stories = pgTable(
  "stories",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    excerpt: varchar("excerpt"),
    content: jsonb("content"),
    featuredImage: integer("featured_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    author: integer("author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    category: integer("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    publishedDate: timestamp("published_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    seo_seoTitle: varchar("seo_seo_title"),
    seo_seoDescription: varchar("seo_seo_description"),
    seo_canonicalUrl: varchar("seo_canonical_url"),
    seo_noindex: boolean("seo_noindex").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_stories_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("stories_slug_idx").on(columns.slug),
    index("stories_featured_image_idx").on(columns.featuredImage),
    index("stories_author_idx").on(columns.author),
    index("stories_category_idx").on(columns.category),
    index("stories_updated_at_idx").on(columns.updatedAt),
    index("stories_created_at_idx").on(columns.createdAt),
    index("stories__status_idx").on(columns._status),
  ],
);

export const stories_rels = pgTable(
  "stories_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    tagsID: integer("tags_id"),
  },
  (columns) => [
    index("stories_rels_order_idx").on(columns.order),
    index("stories_rels_parent_idx").on(columns.parent),
    index("stories_rels_path_idx").on(columns.path),
    index("stories_rels_tags_id_idx").on(columns.tagsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [stories.id],
      name: "stories_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "stories_rels_tags_fk",
    }).onDelete("cascade"),
  ],
);

export const _stories_v = pgTable(
  "_stories_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => stories.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_excerpt: varchar("version_excerpt"),
    version_content: jsonb("version_content"),
    version_featuredImage: integer("version_featured_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_author: integer("version_author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    version_category: integer("version_category_id").references(
      () => categories.id,
      {
        onDelete: "set null",
      },
    ),
    version_publishedDate: timestamp("version_published_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_seo_seoTitle: varchar("version_seo_seo_title"),
    version_seo_seoDescription: varchar("version_seo_seo_description"),
    version_seo_canonicalUrl: varchar("version_seo_canonical_url"),
    version_seo_noindex: boolean("version_seo_noindex").default(false),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__stories_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_stories_v_parent_idx").on(columns.parent),
    index("_stories_v_version_version_slug_idx").on(columns.version_slug),
    index("_stories_v_version_version_featured_image_idx").on(
      columns.version_featuredImage,
    ),
    index("_stories_v_version_version_author_idx").on(columns.version_author),
    index("_stories_v_version_version_category_idx").on(
      columns.version_category,
    ),
    index("_stories_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_stories_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_stories_v_version_version__status_idx").on(columns.version__status),
    index("_stories_v_created_at_idx").on(columns.createdAt),
    index("_stories_v_updated_at_idx").on(columns.updatedAt),
    index("_stories_v_latest_idx").on(columns.latest),
  ],
);

export const _stories_v_rels = pgTable(
  "_stories_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    tagsID: integer("tags_id"),
  },
  (columns) => [
    index("_stories_v_rels_order_idx").on(columns.order),
    index("_stories_v_rels_parent_idx").on(columns.parent),
    index("_stories_v_rels_path_idx").on(columns.path),
    index("_stories_v_rels_tags_id_idx").on(columns.tagsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_stories_v.id],
      name: "_stories_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "_stories_v_rels_tags_fk",
    }).onDelete("cascade"),
  ],
);

export const categories = pgTable(
  "categories",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    description: varchar("description"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("categories_slug_idx").on(columns.slug),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ],
);

export const tags = pgTable(
  "tags",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("tags_slug_idx").on(columns.slug),
    index("tags_updated_at_idx").on(columns.updatedAt),
    index("tags_created_at_idx").on(columns.createdAt),
  ],
);

export const industries = pgTable(
  "industries",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("industries_slug_idx").on(columns.slug),
    index("industries_updated_at_idx").on(columns.updatedAt),
    index("industries_created_at_idx").on(columns.createdAt),
  ],
);

export const organizations = pgTable(
  "organizations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    type: enum_organizations_type("type").notNull(),
    location: varchar("location"),
    website: varchar("website"),
    logo: integer("logo_id").references((): AnyPgColumn => media.id, {
      onDelete: "set null",
    }),
    parentOrganization: integer("parent_organization_id").references(
      (): AnyPgColumn => organizations.id,
      {
        onDelete: "set null",
      },
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("organizations_slug_idx").on(columns.slug),
    index("organizations_logo_idx").on(columns.logo),
    index("organizations_parent_organization_idx").on(
      columns.parentOrganization,
    ),
    index("organizations_updated_at_idx").on(columns.updatedAt),
    index("organizations_created_at_idx").on(columns.createdAt),
  ],
);

export const startups_team = pgTable(
  "startups_team",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    founder: integer("founder_id")
      .notNull()
      .references(() => founders.id, {
        onDelete: "set null",
      }),
    role: enum_startups_team_role("role").notNull(),
    isPrimary: boolean("is_primary").default(false),
  },
  (columns) => [
    index("startups_team_order_idx").on(columns._order),
    index("startups_team_parent_id_idx").on(columns._parentID),
    index("startups_team_founder_idx").on(columns.founder),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [startups.id],
      name: "startups_team_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const startups_opportunities = pgTable(
  "startups_opportunities",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    type: enum_startups_opportunities_type("type").notNull(),
    title: varchar("title").notNull(),
    description: varchar("description"),
    link: varchar("link"),
  },
  (columns) => [
    index("startups_opportunities_order_idx").on(columns._order),
    index("startups_opportunities_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [startups.id],
      name: "startups_opportunities_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const startups = pgTable(
  "startups",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    tagline: varchar("tagline"),
    description: jsonb("description"),
    website: varchar("website"),
    industry: integer("industry_id").references(() => industries.id, {
      onDelete: "set null",
    }),
    stage: enum_startups_stage("stage"),
    city: varchar("city"),
    state: varchar("state"),
    country: varchar("country"),
    teamSize: numeric("team_size", { mode: "number" }),
    fundingStatus: varchar("funding_status"),
    foundedYear: numeric("founded_year", { mode: "number" }),
    womenLed: boolean("women_led").default(false),
    isHiring: boolean("is_hiring").default(false),
    isRaising: boolean("is_raising").default(false),
    isLookingForCoFounder: boolean("is_looking_for_co_founder").default(false),
    owner: integer("owner_id").references(() => founders.id, {
      onDelete: "set null",
    }),
    claim_claimedBy: integer("claim_claimed_by_id").references(
      () => founders.id,
      {
        onDelete: "set null",
      },
    ),
    claim_claimedAt: timestamp("claim_claimed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    claim_claimStatus:
      enum_startups_claim_claim_status("claim_claim_status").default(
        "unclaimed",
      ),
    needsReview: boolean("needs_review").default(false),
    moderationStatus: enum_startups_moderation_status("moderation_status")
      .notNull()
      .default("draft"),
    verificationStatus: enum_startups_verification_status("verification_status")
      .notNull()
      .default("pending"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("startups_slug_idx").on(columns.slug),
    index("startups_logo_idx").on(columns.logo),
    index("startups_industry_idx").on(columns.industry),
    index("startups_stage_idx").on(columns.stage),
    index("startups_city_idx").on(columns.city),
    index("startups_women_led_idx").on(columns.womenLed),
    index("startups_is_hiring_idx").on(columns.isHiring),
    index("startups_is_raising_idx").on(columns.isRaising),
    index("startups_is_looking_for_co_founder_idx").on(
      columns.isLookingForCoFounder,
    ),
    index("startups_owner_idx").on(columns.owner),
    index("startups_claim_claim_claimed_by_idx").on(columns.claim_claimedBy),
    index("startups_claim_claim_claim_status_idx").on(
      columns.claim_claimStatus,
    ),
    index("startups_needs_review_idx").on(columns.needsReview),
    index("startups_moderation_status_idx").on(columns.moderationStatus),
    index("startups_verification_status_idx").on(columns.verificationStatus),
    index("startups_updated_at_idx").on(columns.updatedAt),
    index("startups_created_at_idx").on(columns.createdAt),
    index("stage_idx").on(columns.stage),
    index("city_1_idx").on(columns.city),
    index("industry_idx").on(columns.industry),
    index("isHiring_idx").on(columns.isHiring),
    index("isRaising_idx").on(columns.isRaising),
    index("isLookingForCoFounder_idx").on(columns.isLookingForCoFounder),
    index("womenLed_idx").on(columns.womenLed),
    index("moderationStatus_1_idx").on(columns.moderationStatus),
    index("verificationStatus_1_idx").on(columns.verificationStatus),
    index("needsReview_1_idx").on(columns.needsReview),
    index("owner_idx").on(columns.owner),
    index("claim_claimStatus_idx").on(columns.claim_claimStatus),
  ],
);

export const startups_rels = pgTable(
  "startups_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    organizationsID: integer("organizations_id"),
  },
  (columns) => [
    index("startups_rels_order_idx").on(columns.order),
    index("startups_rels_parent_idx").on(columns.parent),
    index("startups_rels_path_idx").on(columns.path),
    index("startups_rels_organizations_id_idx").on(columns.organizationsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [startups.id],
      name: "startups_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["organizationsID"]],
      foreignColumns: [organizations.id],
      name: "startups_rels_organizations_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    foundersID: integer("founders_id"),
    mediaID: integer("media_id"),
    storiesID: integer("stories_id"),
    categoriesID: integer("categories_id"),
    tagsID: integer("tags_id"),
    industriesID: integer("industries_id"),
    organizationsID: integer("organizations_id"),
    startupsID: integer("startups_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_founders_id_idx").on(
      columns.foundersID,
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_stories_id_idx").on(columns.storiesID),
    index("payload_locked_documents_rels_categories_id_idx").on(
      columns.categoriesID,
    ),
    index("payload_locked_documents_rels_tags_id_idx").on(columns.tagsID),
    index("payload_locked_documents_rels_industries_id_idx").on(
      columns.industriesID,
    ),
    index("payload_locked_documents_rels_organizations_id_idx").on(
      columns.organizationsID,
    ),
    index("payload_locked_documents_rels_startups_id_idx").on(
      columns.startupsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["foundersID"]],
      foreignColumns: [founders.id],
      name: "payload_locked_documents_rels_founders_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["storiesID"]],
      foreignColumns: [stories.id],
      name: "payload_locked_documents_rels_stories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "payload_locked_documents_rels_tags_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["industriesID"]],
      foreignColumns: [industries.id],
      name: "payload_locked_documents_rels_industries_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["organizationsID"]],
      foreignColumns: [organizations.id],
      name: "payload_locked_documents_rels_organizations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["startupsID"]],
      foreignColumns: [startups.id],
      name: "payload_locked_documents_rels_startups_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    foundersID: integer("founders_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    index("payload_preferences_rels_founders_id_idx").on(columns.foundersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["foundersID"]],
      foreignColumns: [founders.id],
      name: "payload_preferences_rels_founders_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_founders_sessions = relations(
  founders_sessions,
  ({ one }) => ({
    _parentID: one(founders, {
      fields: [founders_sessions._parentID],
      references: [founders.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_founders_rels = relations(founders_rels, ({ one }) => ({
  parent: one(founders, {
    fields: [founders_rels.parent],
    references: [founders.id],
    relationName: "_rels",
  }),
  industriesID: one(industries, {
    fields: [founders_rels.industriesID],
    references: [industries.id],
    relationName: "industries",
  }),
  organizationsID: one(organizations, {
    fields: [founders_rels.organizationsID],
    references: [organizations.id],
    relationName: "organizations",
  }),
  startupsID: one(startups, {
    fields: [founders_rels.startupsID],
    references: [startups.id],
    relationName: "startups",
  }),
}));
export const relations_founders = relations(founders, ({ one, many }) => ({
  avatar: one(media, {
    fields: [founders.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  verificationSource_organization: one(organizations, {
    fields: [founders.verificationSource_organization],
    references: [organizations.id],
    relationName: "verificationSource_organization",
  }),
  sessions: many(founders_sessions, {
    relationName: "sessions",
  }),
  _rels: many(founders_rels, {
    relationName: "_rels",
  }),
}));
export const relations_media = relations(media, ({ one }) => ({
  uploadedBy: one(founders, {
    fields: [media.uploadedBy],
    references: [founders.id],
    relationName: "uploadedBy",
  }),
}));
export const relations_stories_rels = relations(stories_rels, ({ one }) => ({
  parent: one(stories, {
    fields: [stories_rels.parent],
    references: [stories.id],
    relationName: "_rels",
  }),
  tagsID: one(tags, {
    fields: [stories_rels.tagsID],
    references: [tags.id],
    relationName: "tags",
  }),
}));
export const relations_stories = relations(stories, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [stories.featuredImage],
    references: [media.id],
    relationName: "featuredImage",
  }),
  author: one(users, {
    fields: [stories.author],
    references: [users.id],
    relationName: "author",
  }),
  category: one(categories, {
    fields: [stories.category],
    references: [categories.id],
    relationName: "category",
  }),
  _rels: many(stories_rels, {
    relationName: "_rels",
  }),
}));
export const relations__stories_v_rels = relations(
  _stories_v_rels,
  ({ one }) => ({
    parent: one(_stories_v, {
      fields: [_stories_v_rels.parent],
      references: [_stories_v.id],
      relationName: "_rels",
    }),
    tagsID: one(tags, {
      fields: [_stories_v_rels.tagsID],
      references: [tags.id],
      relationName: "tags",
    }),
  }),
);
export const relations__stories_v = relations(_stories_v, ({ one, many }) => ({
  parent: one(stories, {
    fields: [_stories_v.parent],
    references: [stories.id],
    relationName: "parent",
  }),
  version_featuredImage: one(media, {
    fields: [_stories_v.version_featuredImage],
    references: [media.id],
    relationName: "version_featuredImage",
  }),
  version_author: one(users, {
    fields: [_stories_v.version_author],
    references: [users.id],
    relationName: "version_author",
  }),
  version_category: one(categories, {
    fields: [_stories_v.version_category],
    references: [categories.id],
    relationName: "version_category",
  }),
  _rels: many(_stories_v_rels, {
    relationName: "_rels",
  }),
}));
export const relations_categories = relations(categories, () => ({}));
export const relations_tags = relations(tags, () => ({}));
export const relations_industries = relations(industries, () => ({}));
export const relations_organizations = relations(organizations, ({ one }) => ({
  logo: one(media, {
    fields: [organizations.logo],
    references: [media.id],
    relationName: "logo",
  }),
  parentOrganization: one(organizations, {
    fields: [organizations.parentOrganization],
    references: [organizations.id],
    relationName: "parentOrganization",
  }),
}));
export const relations_startups_team = relations(startups_team, ({ one }) => ({
  _parentID: one(startups, {
    fields: [startups_team._parentID],
    references: [startups.id],
    relationName: "team",
  }),
  founder: one(founders, {
    fields: [startups_team.founder],
    references: [founders.id],
    relationName: "founder",
  }),
}));
export const relations_startups_opportunities = relations(
  startups_opportunities,
  ({ one }) => ({
    _parentID: one(startups, {
      fields: [startups_opportunities._parentID],
      references: [startups.id],
      relationName: "opportunities",
    }),
  }),
);
export const relations_startups_rels = relations(startups_rels, ({ one }) => ({
  parent: one(startups, {
    fields: [startups_rels.parent],
    references: [startups.id],
    relationName: "_rels",
  }),
  organizationsID: one(organizations, {
    fields: [startups_rels.organizationsID],
    references: [organizations.id],
    relationName: "organizations",
  }),
}));
export const relations_startups = relations(startups, ({ one, many }) => ({
  logo: one(media, {
    fields: [startups.logo],
    references: [media.id],
    relationName: "logo",
  }),
  industry: one(industries, {
    fields: [startups.industry],
    references: [industries.id],
    relationName: "industry",
  }),
  team: many(startups_team, {
    relationName: "team",
  }),
  owner: one(founders, {
    fields: [startups.owner],
    references: [founders.id],
    relationName: "owner",
  }),
  claim_claimedBy: one(founders, {
    fields: [startups.claim_claimedBy],
    references: [founders.id],
    relationName: "claim_claimedBy",
  }),
  opportunities: many(startups_opportunities, {
    relationName: "opportunities",
  }),
  _rels: many(startups_rels, {
    relationName: "_rels",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    foundersID: one(founders, {
      fields: [payload_locked_documents_rels.foundersID],
      references: [founders.id],
      relationName: "founders",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    storiesID: one(stories, {
      fields: [payload_locked_documents_rels.storiesID],
      references: [stories.id],
      relationName: "stories",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: "tags",
    }),
    industriesID: one(industries, {
      fields: [payload_locked_documents_rels.industriesID],
      references: [industries.id],
      relationName: "industries",
    }),
    organizationsID: one(organizations, {
      fields: [payload_locked_documents_rels.organizationsID],
      references: [organizations.id],
      relationName: "organizations",
    }),
    startupsID: one(startups, {
      fields: [payload_locked_documents_rels.startupsID],
      references: [startups.id],
      relationName: "startups",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    foundersID: one(founders, {
      fields: [payload_preferences_rels.foundersID],
      references: [founders.id],
      relationName: "founders",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role;
  enum_founders_gender: typeof enum_founders_gender;
  enum_founders_moderation_status: typeof enum_founders_moderation_status;
  enum_founders_verification_status: typeof enum_founders_verification_status;
  enum_founders_verification_source_type: typeof enum_founders_verification_source_type;
  enum_stories_status: typeof enum_stories_status;
  enum__stories_v_version_status: typeof enum__stories_v_version_status;
  enum_organizations_type: typeof enum_organizations_type;
  enum_startups_team_role: typeof enum_startups_team_role;
  enum_startups_opportunities_type: typeof enum_startups_opportunities_type;
  enum_startups_stage: typeof enum_startups_stage;
  enum_startups_claim_claim_status: typeof enum_startups_claim_claim_status;
  enum_startups_moderation_status: typeof enum_startups_moderation_status;
  enum_startups_verification_status: typeof enum_startups_verification_status;
  users_sessions: typeof users_sessions;
  users: typeof users;
  founders_sessions: typeof founders_sessions;
  founders: typeof founders;
  founders_rels: typeof founders_rels;
  media: typeof media;
  stories: typeof stories;
  stories_rels: typeof stories_rels;
  _stories_v: typeof _stories_v;
  _stories_v_rels: typeof _stories_v_rels;
  categories: typeof categories;
  tags: typeof tags;
  industries: typeof industries;
  organizations: typeof organizations;
  startups_team: typeof startups_team;
  startups_opportunities: typeof startups_opportunities;
  startups: typeof startups;
  startups_rels: typeof startups_rels;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_founders_sessions: typeof relations_founders_sessions;
  relations_founders_rels: typeof relations_founders_rels;
  relations_founders: typeof relations_founders;
  relations_media: typeof relations_media;
  relations_stories_rels: typeof relations_stories_rels;
  relations_stories: typeof relations_stories;
  relations__stories_v_rels: typeof relations__stories_v_rels;
  relations__stories_v: typeof relations__stories_v;
  relations_categories: typeof relations_categories;
  relations_tags: typeof relations_tags;
  relations_industries: typeof relations_industries;
  relations_organizations: typeof relations_organizations;
  relations_startups_team: typeof relations_startups_team;
  relations_startups_opportunities: typeof relations_startups_opportunities;
  relations_startups_rels: typeof relations_startups_rels;
  relations_startups: typeof relations_startups;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
